import React from 'react';
import {
  Heart,
  HeartBreak,
  MagnifyingGlass,
  User,
  ChatCircle,
  Book,
  Play,
  Gear,
  Plus,
  Minus,
  Microphone,
  Check,
  X,
  VideoCamera,
  Camera,
  FileText,
  Image,
  Sparkle,
  Trash,
  PencilSimple,
  Paperclip,
  CaretRight,
  CaretLeft,
  CaretDown,
  CaretUp,
  ArrowsClockwise,
  Star,
  TrendUp,
  SignOut,
  Lock,
  LockOpen,
  List,
  Target,
  Lightning,
  Trophy,
  Medal,
  Shuffle,
  Clock,
  Link,
  Copy,
  Envelope,
  ListBullets,
  UserPlus,
  Bell,
  Upload,
  Users,
  SpeakerHigh,
  SpeakerSlash,
  SpeakerLow,
  Gift,
  Moon,
  Coffee,
  Question,
  GameController,
  ArrowLeft,
  BookOpen,
  Pause,
  Square,
  Bug,
  Globe,
  InstagramLogo,
  ArrowSquareOut,
  ChartBar,
  Lightbulb,
  PaperPlaneTilt,
  Warning,
  WarningCircle,
  Robot,
  Keyboard,
  CheckCircle,
  Stack,
  Cards,
  Leaf,
  Bird,
  Fire,
  HandFist,
  Palette,
  DeviceMobile,
  DownloadSimple,
  IconWeight,
} from '@phosphor-icons/react';

// Get the current icon weight from the document's data attribute
// This is set by the applyTheme function based on font weight preference
const getIconWeight = (): IconWeight => {
  if (typeof document === 'undefined') return 'regular';
  return (document.documentElement.dataset.iconWeight as IconWeight) || 'regular';
};

// Icon wrapper that applies the current weight
const createIcon = (IconComponent: React.ComponentType<any>) => {
  return (props: any) => <IconComponent weight={getIconWeight()} {...props} />;
};

export const ICONS = {
  Heart: createIcon(Heart),
  Search: createIcon(MagnifyingGlass),
  User: createIcon(User),
  MessageCircle: createIcon(ChatCircle),
  Book: createIcon(Book),
  Play: createIcon(Play),
  Settings: createIcon(Gear),
  Plus: createIcon(Plus),
  Minus: createIcon(Minus),
  Mic: createIcon(Microphone),
  Check: createIcon(Check),
  X: createIcon(X),
  Video: createIcon(VideoCamera),
  Camera: createIcon(Camera),
  FileText: createIcon(FileText),
  Image: createIcon(Image),
  Sparkles: createIcon(Sparkle),
  Trash: createIcon(Trash),
  Pencil: createIcon(PencilSimple),
  Paperclip: createIcon(Paperclip),
  ChevronRight: createIcon(CaretRight),
  ChevronLeft: createIcon(CaretLeft),
  ChevronDown: createIcon(CaretDown),
  ChevronUp: createIcon(CaretUp),
  RefreshCw: createIcon(ArrowsClockwise),
  Star: createIcon(Star),
  TrendingUp: createIcon(TrendUp),
  LogOut: createIcon(SignOut),
  Lock: createIcon(Lock),
  Unlock: createIcon(LockOpen),
  List: createIcon(List),
  Target: createIcon(Target),
  Zap: createIcon(Lightning),
  Trophy: createIcon(Trophy),
  Award: createIcon(Medal),
  Shuffle: createIcon(Shuffle),
  Clock: createIcon(Clock),
  Link: createIcon(Link),
  Copy: createIcon(Copy),
  Mail: createIcon(Envelope),
  Menu: createIcon(ListBullets),
  UserPlus: createIcon(UserPlus),
  Bell: createIcon(Bell),
  Upload: createIcon(Upload),
  Users: createIcon(Users),
  Volume2: createIcon(SpeakerHigh),
  VolumeX: createIcon(SpeakerSlash),
  Gift: createIcon(Gift),
  Moon: createIcon(Moon),
  Coffee: createIcon(Coffee),
  HelpCircle: createIcon(Question),
  Gamepad2: createIcon(GameController),
  ArrowLeft: createIcon(ArrowLeft),
  BookOpen: createIcon(BookOpen),
  Pause: createIcon(Pause),
  Square: createIcon(Square),
  Bug: createIcon(Bug),
  Globe: createIcon(Globe),
  Instagram: createIcon(InstagramLogo),
  ExternalLink: createIcon(ArrowSquareOut),
  BarChart: createIcon(ChartBar),
  Lightbulb: createIcon(Lightbulb),
  Send: createIcon(PaperPlaneTilt),
  AlertTriangle: createIcon(Warning),
  Bot: createIcon(Robot),
  Type: createIcon(Keyboard),
  CheckCircle: createIcon(CheckCircle),
  Layers: createIcon(Stack),
  Cards: createIcon(Cards),
  Leaf: createIcon(Leaf),
  Bird: createIcon(Bird),
  Fire: createIcon(Fire),
  Fist: createIcon(HandFist),
  Palette: createIcon(Palette),
  Smartphone: createIcon(DeviceMobile),
  Volume1: createIcon(SpeakerLow),
  Download: createIcon(DownloadSimple),
  HeartCrack: createIcon(HeartBreak),
  AlertCircle: createIcon(WarningCircle),
};
